"""Initial schema

Revision ID: 07e38a47e7ca
Revises: 
Create Date: 2026-10-08 01:44:54.473569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e38a47e7ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_repo_tag_uc', 'releases', ['repository_id', 'tag_name'])
    op.create_unique_constraint('_owner_name_uc', 'repositories', ['owner', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_owner_name_uc', 'repositories', type_='unique')
    op.drop_constraint('_repo_tag_uc', 'releases', type_='unique')
    # ### end Alembic commands ###
